# Generated by Django 5.0.6 on 2024-07-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='book',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='books',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='book',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='books',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='book',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
